export interface ClientLogo {
    id: string;
    url: string;
    alt: string;
}

export const CLIENTS_DATA: ClientLogo[] = [
    { id: "1", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/adictive.jpg", alt: "adictive our clients" },
    { id: "2", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/marketplace.jpg", alt: "marketplace our clients" },
    { id: "3", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/swstrade.jpg", alt: "swstrade our clients" },
    { id: "4", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/pocketlondon.jpg", alt: "pocketlondon our clients" },
    { id: "5", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/IVY.jpg", alt: "IVY our clients" },
    { id: "6", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/pogo-club-Coo.jpg", alt: "pogo club coo our clients" },
    { id: "7", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/Dublin.jpg", alt: "Dublin our clients" },
    { id: "8", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/flash-inspect.jpg", alt: "flash inspect our clients" },
    { id: "9", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2016/10/ibooked-online.jpg.orig", alt: "ibooked online our clients" },
    { id: "10", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/nun-tv.jpg", alt: "nun tv our clients" },
    { id: "11", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/E-S-values.jpg", alt: "E S values our clients" },
    { id: "12", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/failte-ireland.jpg", alt: "failte ireland our clients" },
    { id: "13", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/bookweb.jpg", alt: "bookweb our clients" },
    { id: "14", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/buddy-calc.jpg", alt: "buddy calc our clients" },
    { id: "15", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/kazoom.jpg", alt: "kazoom our clients" },
    { id: "16", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/mike-candys.jpg", alt: "mike candys our clients" },
    { id: "17", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/go-or-no.jpg", alt: "go or no our clients" },
    { id: "18", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/wotspot.jpg", alt: "wotspot our clients" },
    { id: "19", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/sosyologger.jpg", alt: "sosyologger our clients" },
    { id: "20", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/paycomm.jpg", alt: "paycomm our clients" },
    { id: "21", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/IBT-interfaces.jpg", alt: "IBT interfaces our clients" },
    { id: "22", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/mindapps.jpg", alt: "mindapps our clients" },
    { id: "23", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/koni.jpg", alt: "koni our clients" },
    { id: "24", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/ilessonplanner.jpg", alt: "ilessonplanner our clients" },
    { id: "25", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/virtutis.jpg", alt: "virtutis our clients" },
    { id: "26", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/Horoscope.jpg", alt: "Horoscope our clients" },
    { id: "27", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/carbodybids.jpg", alt: "carbodybids our clients" },
    { id: "28", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/voog.jpg", alt: "voog our clients" },
    { id: "29", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/stavanger-auto.jpg", alt: "stavanger auto our clients" },
    { id: "30", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/qanda.jpg", alt: "qanda our clients" },
    { id: "31", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/guesstheprice.jpg", alt: "guesstheprice our clients" },
    { id: "32", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/visit-dublin.jpg", alt: "visit dublin our clients" },
    { id: "33", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/DO.jpg", alt: "DO our clients" },
    { id: "34", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/squadit.jpg", alt: "squadit our clients" },
    { id: "35", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/drenthe.jpg", alt: "drenthe our clients" },
    { id: "36", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/activism.jpg", alt: "activism our clients" },
    { id: "37", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/jupper.jpg", alt: "jupper our clients" },
    { id: "38", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/photobud.jpg", alt: "photobud our clients" },
    { id: "39", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/landri-therm.jpg", alt: "landri therm our clients" },
    { id: "40", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/xpenditure.jpg", alt: "our clients" },
    { id: "41", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/cash-quizz.jpg", alt: "cash quizz our clients" },
    { id: "42", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/istudy.jpg", alt: "istudy our clients" },
    { id: "43", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/fymas-aps.jpg", alt: "fymas aps our clients" },
    { id: "44", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/painting.jpg", alt: "painting our clients" },
    { id: "45", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/sorteamus.jpg", alt: "sorteamus our clients" },
    { id: "46", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/centurus-one.jpg", alt: "centurus one our clients" },
    { id: "47", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/neoxeo.jpg", alt: "our clients" },
    { id: "48", url: "https://www.hiddenbrains.co.uk/wp-content/uploads/2021/05/parken.jpg", alt: "testimonials - hidden brains uk" },
];
